name = "edge-chat-demo"
type = "javascript"
workers_dev = true
compatibility_date = "2021-11-08"
# Add your account ID here
account_id = ""

[build]
command = "yarn build"
[build.upload]
format = "modules"
dir = "dist"
main = "./index.js"
rules = [{type = "Data", globs = ["**/*.html", "**/*.css"]}]

[durable_objects]
bindings = [
  { name = "rooms", class_name = "ChatRoom" }
]

# Indicate that you want the ChatRoom and RateLimiter classes to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom"]
